version: '3'

services:
    restapi:
        build: ./api
        command: python -u api.py
        volumes:
            - ./api:/api
        ports:
            - "5001:5000"
    gudb:
        build: ./gudb
        command: python -u gudb.py
        volumes:
            - ./gudb:/gudb
        ports:
            - "5002:5000"
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'test_pass'
            MYSQL_USER: 'test'
            MYSQL_PASSWORD: 'pass'
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata: